#!/usr/bin/env python
# -*- coding: utf-8 -*-

__license__   = 'All original files are public domain'
__author__    = 'Caio Begotti'
__email__     = 'caio1982@gmail.com'
__credits__   = ['']

"""
Panfolio is a tiny Python script to generate a nice
simple gallery of all your vacations photos
"""

import os
import sys
import mimetypes
import argparse
import glob

import Image as image

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--dir', help='your photos directory')
args = parser.parse_args()

def main():
    size = 128, 128
    allimages = args.dir + '/*'
    outpath = args.dir + '.panfolio'
    if not os.path.exists(outpath):
        os.makedirs(outpath)
    else:
        print 'Thumbnails directory %s not empty, creation skipped' % outpath

    for filepath in glob.glob(allimages):
        type = mimetypes.guess_type(filepath)[0]
        filename = os.path.split(filepath)[1]
        thumbnail = '.panfolio/%s' % filename
        if type and 'image' in type:
            try:
                i = image.open(filepath)
                i.thumbnail(size, image.ANTIALIAS)
                i.save(args.dir + thumbnail, 'PNG')
            except IOError:
                print 'Thumbnailing failed for %s' % filepath
            print "\t<div class='item'><a href='%s'><img class='thumbnail' src='%s' /></a></div>"  % (filename, thumbnail)
        else:
            print "Skipping file %s (it's not an image)" % filepath

if __name__ == '__main__':
    if not args.dir:
        parser.print_help()
        sys.exit(2)
    main()
    sys.exit(0)
